Several improvments

diff --git a/notion-wc b/notion-wc
--- a/notion-wc
+++ b/notion-wc
@@ -2,23 +2,31 @@
 # Input: zipped markdown export from notion
 
 if [ $# -eq 0 ]; then
-  echo "First argument should be path to a zipped markdown export from notion"
+  echo "Supply path(s) to zipped markdown export from notion"
   exit 1
 fi
 
-abs_path="$PWD/$1"
-tmpdir="/tmp/notion-wc/$(date)"
-mkdir -p "$tmpdir"
-cd "$tmpdir"
-if command -v ditto > /dev/null; then
-  if ! ditto_log=$(ditto -V -x -k --sequesterRsrc --rsrc "$abs_path" . 2>&1); then
-    echo "Unzipping failed:\n$ditto_log"
-    exit 1
+initial_dir="$PWD"
+
+for input_file in "$@"; do
+  abs_path="$initial_dir/$input_file"
+  uuid=$(od -x /dev/urandom | head -1 | awk '{OFS="-"; print $2$3,$4,$5,$6,$7$8$9}')
+  tmpdir="/tmp/.notion-wc/$uuid"
+  mkdir -p "$tmpdir"
+  cd "$tmpdir"
+  if command -v ditto > /dev/null; then
+    if ! ditto_log=$(ditto -V -x -k --sequesterRsrc --rsrc "$abs_path" . 2>&1); then
+      echo "Unzipping failed:\n$ditto_log"
+      exit 1
+    fi
+  else
+    unzip "$abs_path" > /dev/null
   fi
-else
-  unzip "$abs_path" > /dev/null
-fi
-find . | grep "\.md$" | while read f; do
-  wc -w "$f"
-done | grep -o "^\s\+\d\+\s" | paste -sd+ - | bc
-rm -rf "$tmpdir"
+  if ! [ $# -eq 1 ]; then
+    printf "$input_file:	"
+  fi
+  find . | grep "\.md$" | while read f; do
+    wc -w "$f"
+  done | grep -o "^\s\+\d\+\s" | paste -sd+ - | bc
+  rm -rf "$tmpdir"
+done
