Added macOS support on set-brightness script

diff --git a/set-brightness b/set-brightness
--- a/set-brightness
+++ b/set-brightness
@@ -1,10 +1,17 @@
 #!/bin/bash
-if [ -d "/sys/class/backlight/intel_backlight" ]; then
-  DIR="/sys/class/backlight/intel_backlight"
-else
-  DIR="/sys/devices/platform/applesmc.768/leds/smc::kbd_backlight"
+if [ `uname` = "Linux" ]; then
+  if [ -d "/sys/class/backlight/intel_backlight" ]; then
+    DIR="/sys/class/backlight/intel_backlight"
+  else
+    DIR="/sys/devices/platform/applesmc.768/leds/smc::kbd_backlight"
+  fi
+  PERCENT=$(( $1 ))
+  MAX=`cat $DIR/max_brightness`
+  NEW=$( awk "BEGIN { pc=${PERCENT}/100; i=int(pc); n=pc*${MAX}; rounded = sprintf(\"%.0f\", n); print rounded }" )
+  sudo sh -c "echo $NEW > $DIR/brightness" /usr/local/bin/set-brightness
+elif [ `uname` = "Darwin" ]; then
+  command -v brew >/dev/null 2>&1 || { echo >&2 "Please install homebrew from https://brew.sh.  Aborting."; exit 1; }
+  command -v brightness >/dev/null 2>&1 || { echo >&2 "Please install \`brightness\` by typing \`brew install brightness\`.  Aborting."; exit 1; }
+  NEW_BRIGHTNESS=`printf "%.2f\n" "$(bc -l <<< "($1 / 100)")"`
+  brightness $NEW_BRIGHTNESS
 fi
-PERCENT=$(( $1 ))
-MAX=`cat $DIR/max_brightness`
-NEW=$( awk "BEGIN { pc=${PERCENT}/100; i=int(pc); n=pc*${MAX}; rounded = sprintf(\"%.0f\", n); print rounded }" )
-sudo sh -c "echo $NEW > $DIR/brightness" /usr/local/bin/set-brightness
